---
# handlers file for glpi_installer
- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
- name: restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
- name: Reboot
  ansible.builtin.command:
    cmd: reboot
