

- name: Wait for MySQL socket to be available
  wait_for:
    path: /var/run/mysqld/mysqld.sock
    state: started
    delay: 2
- name: Debug var_lib_glpi_files
  debug:
    var: "{{ mysql_root_password }}"

- name: Create .my.cnf
  ansible.builtin.copy:
    content: |
      [client]
      user=root
      password={{ mysql_root_password }}
    dest: /root/.my.cnf
    mode: '0600'
  retries: 3
  delay: 1

- name: Set MariaDB root password
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present

- name: Remove anonymous users
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host_all: true
    state: absent


- name: Remove test database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test
    state: absent

- name: Disallow root login remotely
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    host: localhost
    state: present
    password: "{{ mysql_root_password }}"


- name: Reload privilege tables
  community.mysql.mysql_query:
    query: "FLUSH PRIVILEGES;"
    login_unix_socket: /var/run/mysqld/mysqld.sock



- name: Read timezone
  ansible.builtin.shell: "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql"

- name: Create GLPI user
  community.mysql.mysql_user:
    name: "glpi_user"
    password: "P@ssword123"
    login_host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ mysql_root_password }}"
    priv: "glpi.*:ALL"
    host: "localhost"
    state: present

- name: Create database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "glpi"
    state: present

- name: Download GLPI
  ansible.builtin.get_url:
    url: "https://github.com/glpi-project/glpi/releases/download/10.0.15/glpi-10.0.15.tgz"
    dest: "/var/www/html"
    mode: '0644'

- name: Extract GLPI
  ansible.builtin.unarchive:
    src: "/var/www/html/glpi-10.0.15.tgz"
    dest: "/var/www/html"
    remote_src: true

- name: Create necessary directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0755'
    owner: www-data
    group: www-data
  loop: "{{ create }}"

- name: Configure GLPI
  ansible.builtin.template:
    src: downstream.php.j2
    dest: /var/www/html/glpi/downstream.php
    mode: '0644'

- name: Create '/local_define.php'
  ansible.builtin.file:
    state: touch
    path: /etc/glpi/local_define.php
    mode: "0644"

- name: Configure file
  ansible.builtin.template:
    src: local_define.php.j2
    dest: /etc/glpi/local_define.php
    mode: '0644'
    owner: www-data
    group: www-data

- name: Set permissions for /var/www/html/glpi
  ansible.builtin.find:
    paths: /var/www/html/glpi
  register: glpi_files

- name: Set file permissions for /var/www/html/glpi
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ '0644' if item.isreg else '0755' }}"
  loop: "{{ glpi_files.files }}"
  when: glpi_files.matched > 0

- name: Set permissions for /etc/glpi
  ansible.builtin.find:
    paths: /etc/glpi
  register: etc_glpi_files

- name: Set file permissions for /etc/glpi
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ '0644' if item.isreg else '0755' }}"
  loop: "{{ etc_glpi_files.files }}"
  when: etc_glpi_files.matched > 0

- name: Set permissions for /var/lib/glpi
  ansible.builtin.find:
    paths: /var/lib/glpi
  register: var_lib_glpi_files

- name: Set file permissions for /var/lib/glpi
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ '0644' if item.isreg else '0755' }}"
  loop: "{{ var_lib_glpi_files.files }}"
  when: var_lib_glpi_files.matched > 0

- name: Set permissions for /var/log/glpi
  ansible.builtin.find:
    paths: /var/log/glpi
  register: var_log_glpi_files

- name: Set file permissions for /var/log/glpi
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ '0644' if item.isreg else '0755' }}"
  loop: "{{ var_log_glpi_files.files }}"
  when: var_log_glpi_files.matched > 0

- name: Set permissions for /var/www/html/glpi/marketplace
  ansible.builtin.find:
    paths: /var/www/html/glpi/marketplace
  register: marketplace_files

- name: Set file permissions for /var/www/html/glpi/marketplace
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "{{ '0644' if item.isreg else '0755' }}"
  loop: "{{ marketplace_files.files }}"

- name: VirtualHost dedicated to GLPI
  ansible.builtin.template:
    src: glpi.conf.j2
    dest: /etc/apache2/sites-available/glpi.conf

- name: Enable rewrite module and GLPI site
  ansible.builtin.shell: "a2dissite 000-default && a2enmod rewrite && a2ensite glpi"
  notify: restart apache2

- name: Configure PHP settings
  ansible.builtin.lineinfile:
    path: "/etc/php/8.2/apache2/php.ini"
    regexp: "^({{ item.key }})\\s*=.*$"
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ php_settings | dict2items }}"
  notify: restart apache2

- name: Ensure session.cookie_httponly is set to 'on'
  ansible.builtin.lineinfile:
    path: /etc/php/8.2/apache2/php.ini
    regexp: '^session.cookie_httponly\s*='
    line: session.cookie_httponly = on

- name: Set Permission for /var/www/html/glpi
  ansible.builtin.file:
    path: /var/www/html/glpi/
    owner: www-data
    group: www-data
    mode: '0777'
    recurse: yes
