- name: Update packages
  dnf:
    update_cache: yes
    state: latest

- name: Install packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - httpd
  - mariadb-server

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - httpd
  - mariadb

- name: Install pymsql
  dnf:
    name: python3-PyMySQL
    state: present
